# Generated by Django 5.1.6 on 2025-02-25 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacco_management_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_account_number', models.CharField(max_length=20, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='member',
            name='join_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='MemberAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(editable=False, max_length=8, unique=True)),
                ('national_id', models.CharField(max_length=20, unique=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sacco_management_app.member')),
            ],
        ),
    ]
