# Generated by Django 5.1.6 on 2025-02-25 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sacco_management_app', '0002_usercredentials_alter_member_join_date_memberaccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberaccount',
            name='national_id',
        ),
    ]
