# Generated by Django 5.1.6 on 2025-03-07 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacco_management_app', '0005_alter_contactmessage_id_alter_contactmessage_name_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='contactmessage',
            name='contact_mes_email_a7fb56_idx',
        ),
        migrations.RemoveIndex(
            model_name='contactmessage',
            name='contact_mes_created_eb3e69_idx',
        ),
        migrations.RenameField(
            model_name='contactmessage',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterModelTable(
            name='contactmessage',
            table=None,
        ),
    ]
